apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mmp-api
  name: mmp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mmp-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mmp-api
    spec:
      containers:
      - image: nginx:latest
        name: mmp-api
        ports:
        - containerPort: 16000
        resources: {}
status: {}
