apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mmp-api
  name: mmp-api
spec:
  ports:
  - name: "16000"
    port: 16000
    protocol: TCP
    targetPort: 16000
  selector:
    app: mmp-api
  type: NodePort
status:
  loadBalancer: {}
